apiVersion: apps/v1
kind: Deployment
metadata:
  name: sigo-api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sigo-api-gateway
  template:
    metadata:
      labels:
        app: sigo-api-gateway
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: sigo-api-gateway
        image: docker.io/brunoferreirag/sigo-api-gateway:latest
        ports:
        - containerPort: 8001
          name: sigo-gateway
        resources:
          requests:
            memory: "256Mi"
            cpu: "10m"
          limits:
            memory: "512Mi"
            cpu: "256m"
---
apiVersion: v1
kind: Service
metadata:
  name: sigo-gateway
spec:
  type: LoadBalancer 
  ports:
    - name: sigo-gateway
      protocol: TCP
      port: 8001
  selector:
    app: sigo-api-gateway
---

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    dev.okteto.com/generate-host: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST,DELETE,OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-allow-headers: "authorization"
  name: sigo-api-gateway
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: sigo-gateway
          servicePort: 8001
        path: /
---
